# Generated by Django 3.2.7 on 2021-12-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snipPrice', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Hoofdprijs gewone knipbeurt',
            },
        ),
        migrations.CreateModel(
            name='openedTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openedDay', models.CharField(max_length=30)),
                ('openedTime', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Openings tijden',
            },
        ),
        migrations.CreateModel(
            name='salePrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleName', models.CharField(max_length=30)),
                ('salePrice', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Korting namen en prijzen',
            },
        ),
    ]
