# Generated by Django 3.2.7 on 2021-12-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitemanager', '0002_newsblocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblocks',
            name='borderSelect',
            field=models.CharField(choices=[('Groen', 'Groen'), ('Rood', 'Rood'), ('Blauw', 'Blauw'), ('Geen', 'Geen')], default=0, max_length=255),
            preserve_default=False,
        ),
    ]
