# Generated by Django 3.2.7 on 2021-12-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitemanager', '0004_auto_20211223_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblocks',
            name='borderSelect',
            field=models.CharField(choices=[('Rood', 'Rood'), ('Blauw', 'Blauw'), ('Geen', 'Geen'), ('Groen', 'Groen')], max_length=255),
        ),
        migrations.AlterField(
            model_name='newsblocks',
            name='img',
            field=models.ImageField(blank=True, default='none.png', null=True, upload_to='newsImages'),
        ),
    ]
