# Generated by Django 3.2.7 on 2021-12-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitemanager', '0005_auto_20211223_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblocks',
            name='borderSelect',
            field=models.CharField(choices=[('Blauw', 'Blauw'), ('Rood', 'Rood'), ('Geen', 'Geen'), ('Groen', 'Groen')], max_length=255),
        ),
    ]
